import 'dart:math' as math;
import 'dart:ui';
import 'package:flutter/material.dart';

void main()=>runApp(const App());
class Dish{final String n,e,c,d;final int p;const Dish(this.n,this.e,this.c,this.d,this.p);}
const dishes=[Dish('Truffle Smash','🍔','Burgers','Double beef, truffle aioli and crispy onion.',249),Dish('Fire Chicken','🍕','Pizza','Charred chicken, peppers and hot honey.',329),Dish('Tokyo Ramen','🍜','Bowls','Silky broth, ramen, egg and spring onion.',279),Dish('Crispy Tacos','🌮','Tacos','Crunchy tacos with salsa verde and lime.',219),Dish('Creamy Pasta','🍝','Pasta','Parmesan cream, roasted garlic and herbs.',299),Dish('Berry Bliss','🍓','Dessert','Vanilla cream, berries and pistachio crumble.',189)];

class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(brightness:Brightness.dark,useMaterial3:true,scaffoldBackgroundColor:const Color(0xFF08090D)),home:const Home());}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_Home();}
class _Home extends State<Home> with TickerProviderStateMixin{
 late final AnimationController a=AnimationController(vsync:this,duration:const Duration(seconds:5))..repeat();
 late final AnimationController b=AnimationController(vsync:this,duration:const Duration(milliseconds:1300))..repeat(reverse:true);
 final Map<String,int> cart={};String cat='All';final menuKey=GlobalKey();
 int get count=>cart.values.fold(0,(x,y)=>x+y);
 int get total=>cart.entries.fold(0,(s,e)=>s+dishes.firstWhere((x)=>x.n==e.key).p*e.value);
 @override void dispose(){a.dispose();b.dispose();super.dispose();}
 void add(Dish d)=>setState(()=>cart[d.n]=(cart[d.n]??0)+1);
 @override Widget build(BuildContext c){final w=MediaQuery.sizeOf(c).width,wide=w>850;final list=cat=='All'?dishes:dishes.where((x)=>x.c==cat).toList();return Scaffold(body:Stack(children:[const Backdrop(),SafeArea(child:CustomScrollView(slivers:[
 SliverPadding(padding:EdgeInsets.symmetric(horizontal:wide?w*.08:20,vertical:16),sliver:SliverToBoxAdapter(child:Top(count:count,onCart:()=>showCart(c)))),
 SliverPadding(padding:EdgeInsets.symmetric(horizontal:wide?w*.08:20),sliver:SliverToBoxAdapter(child:Hero(a:a,b:b,onTap:()=>Scrollable.ensureVisible(menuKey.currentContext!,duration:const Duration(milliseconds:700))))),
 SliverPadding(key:menuKey,padding:EdgeInsets.fromLTRB(wide?w*.08:20,10,wide?w*.08:20,14),sliver:const SliverToBoxAdapter(child:Section())),
 SliverPadding(padding:EdgeInsets.symmetric(horizontal:wide?w*.08:20),sliver:SliverToBoxAdapter(child:Categories(value:cat,onChange:(x)=>setState(()=>cat=x)))),
 SliverPadding(padding:EdgeInsets.fromLTRB(wide?w*.08:20,18,wide?w*.08:20,60),sliver:SliverGrid(delegate:SliverChildBuilderDelegate((_,i)=>DishCard(dishes:list[i],onAdd:()=>add(list[i])),childCount:list.length),gridDelegate:SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:wide?3:(w>600?2:1),crossAxisSpacing:18,mainAxisSpacing:18,childAspectRatio:wide?1.05:1.1)))
 ])),if(count>0)Positioned(right:20,bottom:22,child:CartButton(count:count,total:total,onTap:()=>showCart(c)))]));}
 void showCart(BuildContext c)=>showModalBottomSheet(context:c,isScrollControlled:true,backgroundColor:Colors.transparent,builder:(_)=>Cart(cart:cart,total:total,onAdd:add,onRemove:(d)=>setState((){final n=cart[d.n]??0;if(n<=1){cart.remove(d.n);}else{cart[d.n]=n-1;}})));
}
class Top extends StatelessWidget{final int count;final VoidCallback onCart;const Top({super.key,required this.count,required this.onCart});@override Widget build(BuildContext c)=>Row(children:[const Logo(),const SizedBox(width:11),const Text('FOOD CORT',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900,letterSpacing:1.5)),const Spacer(),if(MediaQuery.sizeOf(c).width>700)...[const Nav('Menu'),const SizedBox(width:25),const Nav('Our story'),const SizedBox(width:25),const Nav('Locations'),const SizedBox(width:25)],Stack(clipBehavior:Clip.none,children:[Material(color:Colors.white10,borderRadius:BorderRadius.circular(15),child:InkWell(onTap:onCart,borderRadius:BorderRadius.circular(15),child:const Padding(padding:EdgeInsets.all(13),child:Icon(Icons.shopping_bag_outlined)))),if(count>0)Positioned(right:-5,top:-5,child:CircleAvatar(radius:9,backgroundColor:const Color(0xFFFF5C4D),child:Text(count.toString(),style:const TextStyle(fontSize:9,fontWeight:FontWeight.w900))))])]);}
class Logo extends StatelessWidget{const Logo({super.key});@override Widget build(BuildContext c)=>Container(width:44,height:44,decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFFF8A4C),Color(0xFFFF3D81)]),borderRadius:BorderRadius.circular(14),boxShadow:const[BoxShadow(color:Color(0x66FF5B4D),blurRadius:24)]),child:const Icon(Icons.restaurant_rounded));}
class Nav extends StatelessWidget{final String t;const Nav(this.t,{super.key});@override Widget build(BuildContext c)=>Text(t,style:TextStyle(color:Colors.white.withOpacity(.6),fontWeight:FontWeight.w600));}
class Hero extends StatelessWidget{final AnimationController a,b;final VoidCallback onTap;const Hero({super.key,required this.a,required this.b,required this.onTap});@override Widget build(BuildContext c){final wide=MediaQuery.sizeOf(c).width>760;final copy=Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Pill(),const SizedBox(height:20),const Text('Good food.\nGreat mood.',style:TextStyle(fontSize:56,height:.98,fontWeight:FontWeight.w900,letterSpacing:-2.5)),const SizedBox(height:16),Text('Bold flavours, beautiful plates and a little bit of magic in every bite.',style:TextStyle(fontSize:17,height:1.5,color:Colors.white.withOpacity(.58))),const SizedBox(height:26),FilledButton.icon(onPressed:onTap,style:FilledButton.styleFrom(backgroundColor:const Color(0xFFFF6347),padding:const EdgeInsets.symmetric(horizontal:22,vertical:17),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(17))),icon:const Icon(Icons.arrow_forward_rounded),label:const Text('Explore menu',style:TextStyle(fontWeight:FontWeight.w800)))]);final art=AnimatedBuilder(animation:Listenable.merge([a,b]),builder:(_,__) {final y=math.sin(a.value*math.pi*2)*12;return SizedBox(height:wide?470:360,child:Stack(alignment:Alignment.center,children:[Container(width:350,height:350,decoration:BoxDecoration(shape:BoxShape.circle,gradient:RadialGradient(colors:[const Color(0xFFFF654A).withOpacity(.18+b.value*.08),Colors.transparent]))),Transform.translate(offset:Offset(0,y),child:Transform.rotate(angle:y*.002,child:Container(width:wide?300:245,height:wide?300:245,decoration:BoxDecoration(borderRadius:BorderRadius.circular(80),gradient:const LinearGradient(colors:[Color(0xFFFF7A4A),Color(0xFF6B32FF)]),boxShadow:const[BoxShadow(color:Color(0x805D2BFF),blurRadius:80),BoxShadow(color:Color(0x80FF613D),blurRadius:55)]),child:Center(child:Transform.scale(scale:1+b.value*.025,child:const Text('🍔',style:TextStyle(fontSize:150))))))),const Positioned(top:35,right:12,child:ChipX('FRESH',Icons.eco_rounded)),const Positioned(bottom:40,left:10,child:ChipX('4.9 ★',Icons.star_rounded))]));});return Padding(padding:const EdgeInsets.only(top:38,bottom:20),child:wide?Row(children:[Expanded(child:copy),Expanded(child:art)]):Column(children:[copy,art]));}}
class Pill extends StatelessWidget{const Pill({super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:13,vertical:8),decoration:BoxDecoration(color:const Color(0x22FF704D),borderRadius:BorderRadius.circular(30),border:Border.all(color:const Color(0x55FF704D))),child:const Text('THE NEW WAY TO DINE',style:TextStyle(color:Color(0xFFFF9273),fontSize:11,fontWeight:FontWeight.w900,letterSpacing:1.2)));}
class ChipX extends StatelessWidget{final String t;final IconData i;const ChipX(this.t,this.i,{super.key});@override Widget build(BuildContext c)=>ClipRRect(borderRadius:BorderRadius.circular(18),child:BackdropFilter(filter:ImageFilter.blur(sigmaX:12,sigmaY:12),child:Container(padding:const EdgeInsets.symmetric(horizontal:13,vertical:11),decoration:BoxDecoration(color:Colors.white10,borderRadius:BorderRadius.circular(18),border:Border.all(color:Colors.white12)),child:Row(mainAxisSize:MainAxisSize.min,children:[Icon(i,size:16,color:const Color(0xFFFFB36A)),const SizedBox(width:7),Text(t,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w800))]))));}
class Section extends StatelessWidget{const Section({super.key});@override Widget build(BuildContext c)=>const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('Explore the menu',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),SizedBox(height:5),Text('Crafted for cravings. Made for sharing.',style:TextStyle(color:Colors.white54))]);}
class Categories extends StatelessWidget{final String value;final ValueChanged<String> onChange;const Categories({super.key,required this.value,required this.onChange});@override Widget build(BuildContext c){const x=['All','Burgers','Pizza','Bowls','Tacos','Pasta','Dessert'];return SizedBox(height:58,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:x.length,separatorBuilder:(_,__)=>const SizedBox(width:10),itemBuilder:(_,i){final on=x[i]==value;return AnimatedContainer(duration:const Duration(milliseconds:300),padding:const EdgeInsets.symmetric(horizontal:18),decoration:BoxDecoration(gradient:on?const LinearGradient(colors:[Color(0xFFFF704D),Color(0xFFFF3D81)]):null,color:on?null:Colors.white10,borderRadius:BorderRadius.circular(18)),child:InkWell(onTap:()=>onChange(x[i]),borderRadius:BorderRadius.circular(18),child:Center(child:Text(x[i],style:TextStyle(fontWeight:FontWeight.w800,color:on?Colors.white:Colors.white60)))));})) ;}}
class DishCard extends StatefulWidget{final Dish dishes;final VoidCallback onAdd;const DishCard({super.key,required this.dishes,required this.onAdd});@override State<DishCard> createState()=>_DishCard();}
class _DishCard extends State<DishCard>{bool hover=false;@override Widget build(BuildContext c)=>MouseRegion(onEnter:(_)=>setState(()=>hover=true),onExit:(_)=>setState(()=>hover=false),child:AnimatedScale(scale:hover?1.025:1,duration:const Duration(milliseconds:240),child:Container(decoration:BoxDecoration(color:const Color(0xFF111318),borderRadius:BorderRadius.circular(28),border:Border.all(color:Colors.white12),boxShadow:[BoxShadow(color:hover?const Color(0x332C5AFF):Colors.black38,blurRadius:hover?34:20,offset:const Offset(0,14))]),padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Expanded(child:Center(child:AnimatedScale(scale:hover?1.08:1,duration:const Duration(milliseconds:250),child:Text(widget.dishes.e,style:const TextStyle(fontSize:102))))),Text(widget.dishes.c.toUpperCase(),style:const TextStyle(color:Color(0xFFFF9676),fontSize:9,fontWeight:FontWeight.w900,letterSpacing:1)),const SizedBox(height:8),Text(widget.dishes.n,style:const TextStyle(fontSize:20,fontWeight:FontWeight.w900)),const SizedBox(height:5),Text(widget.dishes.d,maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(color:Colors.white54,fontSize:12,height:1.35)),const SizedBox(height:12),Row(children:[Text('₹'+widget.dishes.p.toString(),style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900)),const Spacer(),Material(color:const Color(0xFFFF6049),borderRadius:BorderRadius.circular(14),child:InkWell(onTap:widget.onAdd,borderRadius:BorderRadius.circular(14),child:const Padding(padding:EdgeInsets.all(11),child:Icon(Icons.add_rounded))))])]))));}
class CartButton extends StatelessWidget{final int count,total;final VoidCallback onTap;const CartButton({super.key,required this.count,required this.total,required this.onTap});@override Widget build(BuildContext c)=>Material(color:Colors.transparent,child:InkWell(onTap:onTap,borderRadius:BorderRadius.circular(22),child:Container(padding:const EdgeInsets.symmetric(horizontal:17,vertical:13),decoration:BoxDecoration(gradient:const LinearGradient(colors:[Color(0xFFFF6B4A),Color(0xFFFF3B78)]),borderRadius:BorderRadius.circular(22),boxShadow:const[BoxShadow(color:Color(0x663F1630),blurRadius:25,offset:Offset(0,10))]),child:Row(mainAxisSize:MainAxisSize.min,children:[CircleAvatar(radius:15,backgroundColor:Colors.white24,child:Text(count.toString(),style:const TextStyle(fontWeight:FontWeight.w900))),const SizedBox(width:10),Text('View cart • ₹'+total.toString(),style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(width:8),const Icon(Icons.arrow_forward_rounded,size:18)]))));}
class Cart extends StatelessWidget{final Map<String,int> cart;final int total;final ValueChanged<Dish> onAdd,onRemove;const Cart({super.key,required this.cart,required this.total,required this.onAdd,required this.onRemove});@override Widget build(BuildContext c)=>DraggableScrollableSheet(initialChildSize:.72,maxChildSize:.92,builder:(_,scroll)=>Container(decoration:const BoxDecoration(color:Color(0xFF101216),borderRadius:BorderRadius.vertical(top:Radius.circular(32))),padding:const EdgeInsets.fromLTRB(22,12,22,20),child:Column(children:[Container(width:45,height:5,decoration:BoxDecoration(color:Colors.white24,borderRadius:BorderRadius.circular(10))),const SizedBox(height:20),const Row(children:[Text('Your cart',style:TextStyle(fontSize:27,fontWeight:FontWeight.w900)),Spacer(),Icon(Icons.shopping_bag_rounded,color:Color(0xFFFF704D))]),const SizedBox(height:14),Expanded(child:ListView(controller:scroll,children:cart.entries.map((e){final d=dishes.firstWhere((x)=>x.n==e.key);return ListTile(leading:Text(d.e,style:const TextStyle(fontSize:34)),title:Text(d.n,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text('₹'+d.p.toString()),trailing:Row(mainAxisSize:MainAxisSize.min,children:[IconButton(onPressed:()=>onRemove(d),icon:const Icon(Icons.remove_circle_outline)),Text(e.value.toString()),IconButton(onPressed:()=>onAdd(d),icon:const Icon(Icons.add_circle_outline))]));}).toList())),Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(color:Colors.white10,borderRadius:BorderRadius.circular(22)),child:Column(children:[Row(children:[const Text('Total',style:TextStyle(color:Colors.white54)),const Spacer(),Text('₹'+total.toString(),style:const TextStyle(fontSize:24,fontWeight:FontWeight.w900))]),const SizedBox(height:14),SizedBox(width:double.infinity,child:FilledButton(onPressed:()=>Navigator.pop(c),style:FilledButton.styleFrom(backgroundColor:const Color(0xFFFF6049),padding:const EdgeInsets.symmetric(vertical:16),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16))),child:const Text('Continue to checkout',style:TextStyle(fontWeight:FontWeight.w900))))]))]));}}
class Backdrop extends StatefulWidget{const Backdrop({super.key});@override State<Backdrop> createState()=>_Backdrop();}
class _Backdrop extends State<Backdrop> with SingleTickerProviderStateMixin{late final AnimationController c=AnimationController(vsync:this,duration:const Duration(seconds:14))..repeat();@override void dispose(){c.dispose();super.dispose();}@override Widget build(BuildContext x)=>AnimatedBuilder(animation:c,builder:(_,__) {final p=math.sin(c.value*math.pi*2)*80;return Stack(children:[Positioned(left:p-120,top:60,child:const Glow(Color(0xFFFF4D5D),310)),Positioned(right:-130-p,top:300,child:const Glow(Color(0xFF5136FF),360)),Positioned.fill(child:IgnorePointer(child:CustomPaint(painter:Grid()))) ]);});}
class Glow extends StatelessWidget{final Color color;final double size;const Glow(this.color,this.size,{super.key});@override Widget build(BuildContext c)=>Container(width:size,height:size,decoration:BoxDecoration(shape:BoxShape.circle,gradient:RadialGradient(colors:[color.withOpacity(.13),Colors.transparent])));}
class Grid extends CustomPainter{@override void paint(Canvas c,Size s){final p=Paint()..color=Colors.white.withOpacity(.018);for(double x=0;x<s.width;x+=42){c.drawLine(Offset(x,0),Offset(x,s.height),p);}for(double y=0;y<s.height;y+=42){c.drawLine(Offset(0,y),Offset(s.width,y),p);}}@override bool shouldRepaint(covariant CustomPainter oldDelegate)=>false;}
